### ISSUE TITLE
Feature selection not working

### ISSUE THREAD

**Issue by karjain** [laihanel/PatternSix#49]
I tried these 2 methods:
'regsubsets' from library("leaps") returned in-correct results.
Tried 'rfeControl' from library(caret). Did not converge due to long training time. Code available in the open pull request to test

Here is good resource for feature selection libraries :
https://www.machinelearningplus.com/machine-learning/feature-selection/

**Comment by laihanel** [comment]
I've tried other methods and they crashed too.

**Comment by karjain** [comment]
rfeControl is not crashing for me but it did not converge for around 1 hr and I had to kill the process.
Is rfeControl  also crashing for you @laihanel ?
